name: GANFingerprints
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.6
  - cudatoolkit=11.3.1
  - tensorflow-gpu>=2.6,<2.12
  - setuptools<65
  - numpy
  - scipy
  - moviepy
  - Pillow
  - scikit-image
  - scikit-learn
  - lmdb
  - matplotlib
#  - opencv-python
  - cryptography
  - h5py
  - six
  - chainer=7.8.1
  - Cython
  - cupy<9
  - PyYAML
  - __cuda==11.8
